move test to integration test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -215,47 +215,6 @@ jobs:
             python3 -m pip install pytorch-quantization==2.1.2 --extra-index-url https://pypi.ngc.nvidia.com
             python3 -m pip install onnx_graphsurgeon==0.3.27   --extra-index-url https://pypi.ngc.nvidia.com
       - run:
-          name: test sweeper
-          no_output_timeout: 30m
-          command: |
-            << parameters.sg_new_env_python_version >> -m venv << parameters.sg_new_env_name >>
-            source << parameters.sg_new_env_name >>/bin/activate
-            python3.8 -m pip install --upgrade setuptools pip wheel
-            python3.8 -m pip install -r requirements.txt
-            python3.8 -m pip install .
-            python3.8 -m pip install torch torchvision torchaudio
-            # Define variables
-            ckpt_root_dir="$PWD" # or specify the full path if different
-            experiment_name="sweep_cifar10"
-            experiment_dir="$ckpt_root_dir/$experiment_name"
-            
-            # Step 1: Make sure that the directory experiment_dir doesn't exist
-            if [ -d "$experiment_dir" ]; then
-              echo "Error: Directory $experiment_dir already exists."
-              exit 1
-            fi
-            
-            # Run the specific Python command
-            expected_num_dir=4
-            python3.8 -m super_gradients.train_from_recipe -m --config-name=cifar10_resnet \
-              experiment_name=TEST_SWEEP_cifar10 \
-              training_hyperparams.initial_lr=0.001,0.01 \
-              training_hyperparams.ema=True,False
-            
-            # Step 3: Make sure that the directory experiment_dir was created. If not, fail
-            if [ ! -d "$experiment_dir" ]; then
-              echo "Error: Directory $experiment_dir was not created."
-              exit 1
-            fi
-            
-            # Step 4: Make sure that experiment_dir includes $expected_num_dir subdirectories. If not, fail
-            subdir_count=$(find "$experiment_dir" -mindepth 1 -maxdepth 1 -type d | wc -l)
-            if [ "$subdir_count" -ne  $expected_num_dir ]; then
-              echo "Error: $experiment_dir should include $expected_num_dir subdirectories but includes $subdir_count."
-              exit 1
-            fi
-
-      - run:
           name: run tests with coverage
           no_output_timeout: 30m
           command: |
@@ -497,6 +456,72 @@ jobs:
           tag: $CIRCLE_TAG
           notes: "This GitHub Release was done automatically by CircleCI"
 
+  hydra_sweeper_test:
+    docker:
+      - image: 307629990626.dkr.ecr.us-east-1.amazonaws.com/deci/infra/circleci/runner/sg-gpu:<< pipeline.parameters.sg_docker_version >>
+    resource_class: deci-ai/sg-gpu-on-premise
+    parameters:
+      sg_existing_env_path:
+        type: string
+        default: "/env/persistent_env"
+      sg_new_env_name:
+        type: string
+        default: "${CIRCLE_BUILD_NUM}"
+      sg_new_env_python_version:
+        type: string
+        default: "python3.8"
+    steps:
+      - checkout
+      - run:
+          name: install requirements and run recipe tests
+          command: |
+            << parameters.sg_new_env_python_version >> -m venv << parameters.sg_new_env_name >>
+            source << parameters.sg_new_env_name >>/bin/activate
+            python3.8 -m pip install --upgrade setuptools pip wheel
+            python3.8 -m pip install -r requirements.txt
+            python3.8 -m pip install .
+            python3.8 -m pip install torch torchvision torchaudio
+            
+            # Define variables
+            ckpt_root_dir="$PWD" # or specify the full path if different
+            experiment_name="sweep_cifar10"
+            experiment_dir="$ckpt_root_dir/$experiment_name"
+
+            # Step 1: Make sure that the directory experiment_dir doesn't exist
+            if [ -d "$experiment_dir" ]; then
+              echo "Error: Directory $experiment_dir already exists."
+              exit 1
+            fi
+
+            # Run the specific Python command
+            expected_num_dir=2
+            python -m super_gradients.train_from_recipe -m --config-name=cifar10_resnet \
+              ckpt_root_dir=$ckpt_root_dir\
+              experiment_name=$experiment_name \
+              training_hyperparams.max_epochs=1\
+              training_hyperparams.initial_lr=0.001,0.01
+
+            # Step 3: Make sure that the directory experiment_dir was created. If not, fail
+            if [ ! -d "$experiment_dir" ]; then
+              echo "Error: Directory $experiment_dir was not created."
+              exit 1
+            fi
+
+            # Step 4: Make sure that experiment_dir includes $expected_num_dir subdirectories. If not, fail
+            subdir_count=$(find "$experiment_dir" -mindepth 1 -maxdepth 1 -type d | wc -l)
+            if [ "$subdir_count" -ne  $expected_num_dir ]; then
+              echo "Error: $experiment_dir should include $expected_num_dir subdirectories but includes $subdir_count."
+              exit 1
+            fi
+      - run:
+          name: Remove new environment when failed
+          command: "rm -r << parameters.sg_new_env_name >>"
+          when: on_fail
+
+      - slack/notify:
+          channel: "sg-integration-tests"
+          event: fail
+          template: basic_fail_1 # see https://github.com/CircleCI-Public/slack-orb/wiki#templates.
 
   recipe_accuracy_tests:
     docker:
@@ -807,6 +832,9 @@ workflows:
   sanity_tests:
     when:  << pipeline.parameters.run_sanity_tests_flow >>
     jobs:
+      - hydra_sweeper_test:
+          context:
+            - slack
       - recipe_sanity_tests_classification_pt1:
           context:
             - slack
@@ -847,6 +875,10 @@ workflows:
             - deci-common/persist_version_info
             - login_to_codeartifact_release
           <<: *release_tag_filter
+      - hydra_sweeper_test:
+          context:
+            - slack
+          <<: *release_tag_filter
       - recipe_sanity_tests_classification_pt1:
           context:
             - slack
@@ -875,6 +907,7 @@ workflows:
           py_version: "3.8"
           requires:
             - "build3.8"
+            - hydra_sweeper_test
             - recipe_accuracy_tests
             - recipe_sanity_tests_classification_pt1
             - recipe_sanity_tests_classification_pt2
