fix indentation

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -215,43 +215,45 @@ jobs:
             python3 -m pip install pytorch-quantization==2.1.2 --extra-index-url https://pypi.ngc.nvidia.com
             python3 -m pip install onnx_graphsurgeon==0.3.27   --extra-index-url https://pypi.ngc.nvidia.com
       - run:
-        command: |
-          << parameters.sg_new_env_python_version >> -m venv << parameters.sg_new_env_name >>
-          source << parameters.sg_new_env_name >>/bin/activate
-          python3.8 -m pip install --upgrade setuptools pip wheel
-          python3.8 -m pip install -r requirements.txt
-          python3.8 -m pip install .
-          python3.8 -m pip install torch torchvision torchaudio
-          # Define variables
-          ckpt_root_dir="$PWD" # or specify the full path if different
-          experiment_name="sweep_cifar10"
-          experiment_dir="$ckpt_root_dir/$experiment_name"
-          
-          # Step 1: Make sure that the directory experiment_dir doesn't exist
-          if [ -d "$experiment_dir" ]; then
-            echo "Error: Directory $experiment_dir already exists."
-            exit 1
-          fi
-          
-          # Run the specific Python command
-          expected_num_dir=4
-          python3.8 -m super_gradients.train_from_recipe -m --config-name=cifar10_resnet \
-            experiment_name=TEST_SWEEP_cifar10 \
-            training_hyperparams.initial_lr=0.001,0.01 \
-            training_hyperparams.ema=True,False
-          
-          # Step 3: Make sure that the directory experiment_dir was created. If not, fail
-          if [ ! -d "$experiment_dir" ]; then
-            echo "Error: Directory $experiment_dir was not created."
-            exit 1
-          fi
-          
-          # Step 4: Make sure that experiment_dir includes $expected_num_dir subdirectories. If not, fail
-          subdir_count=$(find "$experiment_dir" -mindepth 1 -maxdepth 1 -type d | wc -l)
-          if [ "$subdir_count" -ne  $expected_num_dir ]; then
-            echo "Error: $experiment_dir should include $expected_num_dir subdirectories but includes $subdir_count."
-            exit 1
-          fi
+          name: test sweeper
+          no_output_timeout: 30m
+          command: |
+            << parameters.sg_new_env_python_version >> -m venv << parameters.sg_new_env_name >>
+            source << parameters.sg_new_env_name >>/bin/activate
+            python3.8 -m pip install --upgrade setuptools pip wheel
+            python3.8 -m pip install -r requirements.txt
+            python3.8 -m pip install .
+            python3.8 -m pip install torch torchvision torchaudio
+            # Define variables
+            ckpt_root_dir="$PWD" # or specify the full path if different
+            experiment_name="sweep_cifar10"
+            experiment_dir="$ckpt_root_dir/$experiment_name"
+            
+            # Step 1: Make sure that the directory experiment_dir doesn't exist
+            if [ -d "$experiment_dir" ]; then
+              echo "Error: Directory $experiment_dir already exists."
+              exit 1
+            fi
+            
+            # Run the specific Python command
+            expected_num_dir=4
+            python3.8 -m super_gradients.train_from_recipe -m --config-name=cifar10_resnet \
+              experiment_name=TEST_SWEEP_cifar10 \
+              training_hyperparams.initial_lr=0.001,0.01 \
+              training_hyperparams.ema=True,False
+            
+            # Step 3: Make sure that the directory experiment_dir was created. If not, fail
+            if [ ! -d "$experiment_dir" ]; then
+              echo "Error: Directory $experiment_dir was not created."
+              exit 1
+            fi
+            
+            # Step 4: Make sure that experiment_dir includes $expected_num_dir subdirectories. If not, fail
+            subdir_count=$(find "$experiment_dir" -mindepth 1 -maxdepth 1 -type d | wc -l)
+            if [ "$subdir_count" -ne  $expected_num_dir ]; then
+              echo "Error: $experiment_dir should include $expected_num_dir subdirectories but includes $subdir_count."
+              exit 1
+            fi
 
       - run:
         name: run tests with coverage
